
import React, { useState } from 'react';
import { CadConceptData, ThreeDPrimitive } from '../../types';
import { Box, Layers, MousePointer2, Move3d, RotateCcw, Share2, Maximize2, Settings, Info, BoxSelect, Cpu, Leaf, Tag, Wand2, Ruler, Weight, Hammer, Package, Clock, DollarSign, Database, Plus, Scaling, Rotate3d, X } from 'lucide-react';
import { AddComponentModal } from '../Modals/AddComponentModal';
import { Canvas } from '@react-three/fiber';
import { OrbitControls, Grid, Environment, TransformControls } from '@react-three/drei';

interface CadViewProps {
  data: CadConceptData;
  onAction?: (actionPrompt: string) => void;
  onOpenParametric?: (partName: string) => void;
}

const PrimitiveRenderer: React.FC<{ primitive: ThreeDPrimitive }> = ({ primitive }) => {
  const { type, position, rotation, scale, color } = primitive;
  
  switch (type) {
    case 'box':
      return (
        <mesh position={position} rotation={rotation} scale={scale}>
          <boxGeometry args={[1, 1, 1]} />
          <meshStandardMaterial color={color} />
        </mesh>
      );
    case 'sphere':
      return (
        <mesh position={position} rotation={rotation} scale={scale}>
          <sphereGeometry args={[0.5, 32, 32]} />
          <meshStandardMaterial color={color} />
        </mesh>
      );
    case 'cylinder':
      return (
        <mesh position={position} rotation={rotation} scale={scale}>
          <cylinderGeometry args={[0.5, 0.5, 1, 32]} />
          <meshStandardMaterial color={color} />
        </mesh>
      );
    default:
      return null;
  }
};

export const CadView: React.FC<CadViewProps> = ({ data, onAction, onOpenParametric }) => {
  const [activeTab, setActiveTab] = useState<'components' | 'rationale'>('components');
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  const [transformMode, setTransformMode] = useState<'translate' | 'rotate' | 'scale'>('translate');
  const [exportInstruction, setExportInstruction] = useState<'STEP' | 'STL' | null>(null);

  const handleAddComponent = (details: { 
    name: string; 
    category: string; 
    sourcing: 'custom_manufactured' | 'off_the_shelf';
    specs?: string;
    supplier?: string;
    mpn?: string;
    unitCost?: string;
    leadTime?: string;
    notes?: string;
  }) => {
    if (details.sourcing === 'custom_manufactured') {
      onAction?.(`Add a new 'custom_manufactured' component to the concept.
        Name: ${details.name}
        Category: ${details.category}
        Specs: ${details.specs}
        Rationale/Notes: ${details.notes || 'None'}`);
    } else {
      onAction?.(`Add a new 'off_the_shelf' component to the concept.
        Name: ${details.name}
        Category: ${details.category}
        Supplier: ${details.supplier}
        MPN: ${details.mpn}
        Unit Cost: ${details.unitCost}
        Lead Time: ${details.leadTime}
        Rationale/Notes: ${details.notes || 'None'}`);
    }
  };

  const generateOpenSCAD = (primitives: ThreeDPrimitive[]) => {
    let scad = `// Generated by Buildables\n// Use OpenSCAD to export this model to STL or STEP formats.\n\n`;
    scad += `union() {\n`;
    
    primitives.forEach(p => {
      const rotX = p.rotation[0] * (180 / Math.PI);
      const rotY = p.rotation[1] * (180 / Math.PI);
      const rotZ = p.rotation[2] * (180 / Math.PI);
      
      scad += `  translate([${p.position[0]}, ${p.position[1]}, ${p.position[2]}])\n`;
      scad += `  rotate([${rotX}, ${rotY}, ${rotZ}])\n`;
      scad += `  color("${p.color}")\n`;
      
      if (p.type === 'box') {
        scad += `  cube([${p.scale[0]}, ${p.scale[1]}, ${p.scale[2]}], center=true);\n\n`;
      } else if (p.type === 'sphere') {
        scad += `  scale([${p.scale[0]}, ${p.scale[1]}, ${p.scale[2]}]) sphere(r=0.5, $fn=32);\n\n`;
      } else if (p.type === 'cylinder') {
        // Three.js cylinder is along Y axis, OpenSCAD is along Z axis. Rotate to match.
        scad += `  scale([${p.scale[0]}, ${p.scale[1]}, ${p.scale[2]}]) rotate([90, 0, 0]) cylinder(h=1, r=0.5, center=true, $fn=32);\n\n`;
      }
    });
    
    scad += `}\n`;
    return scad;
  };

  const handleExportOpenSCAD = (format: 'STEP' | 'STL') => {
    if (!data.threeDModel) return;
    const scadContent = generateOpenSCAD(data.threeDModel);
    const blob = new Blob([scadContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${data.conceptName.replace(/\s+/g, '_')}.scad`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    setExportInstruction(format);
  };

  return (
    <div className="flex h-full bg-white relative overflow-hidden font-sans">
      
      {exportInstruction && (
        <div className="absolute inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
           <div className="bg-white rounded-2xl shadow-2xl max-w-md w-full p-6 animate-in zoom-in duration-200">
              <div className="flex justify-between items-start mb-4">
                 <h3 className="text-lg font-bold text-brand-darkBlue">Export to {exportInstruction}</h3>
                 <button onClick={() => setExportInstruction(null)} className="text-gray-400 hover:text-gray-600">
                    <X size={20} />
                 </button>
              </div>
              <div className="space-y-4 text-sm text-gray-600">
                 <p>We've downloaded an <strong>OpenSCAD (.scad)</strong> script for your concept.</p>
                 <p>To get your final {exportInstruction} file, follow these steps:</p>
                 <ol className="list-decimal pl-5 space-y-2">
                    <li>Open the downloaded <code>.scad</code> file in <a href="https://openscad.org/" target="_blank" rel="noreferrer" className="text-brand-blue hover:underline">OpenSCAD</a>.</li>
                    <li>Press <strong>F6</strong> to Render the geometry.</li>
                    <li>Go to <strong>File &gt; Export &gt; Export as {exportInstruction}</strong>.</li>
                 </ol>
              </div>
              <div className="mt-6 flex justify-end">
                 <button onClick={() => setExportInstruction(null)} className="px-4 py-2 bg-brand-blue text-white rounded-lg hover:bg-blue-700 font-medium transition-colors">
                    Got it
                 </button>
              </div>
           </div>
        </div>
      )}

      {isAddModalOpen && (
        <AddComponentModal 
            onClose={() => setIsAddModalOpen(false)} 
            onAdd={handleAddComponent} 
        />
      )}

      {/* LEFT: Main 3D Viewport (Simulated) */}
      <div className="flex-1 bg-brand-darkBlue relative flex flex-col">
        
        {/* Viewport Toolbar */}
        <div className="absolute top-4 left-4 z-20 flex flex-col gap-2">
            <div className="bg-slate-800/90 backdrop-blur border border-slate-700 p-2 rounded-lg shadow-xl text-gray-300 flex flex-col gap-1">
                <button 
                    className={`p-2 rounded transition-colors ${transformMode === 'translate' ? 'bg-slate-700 text-white' : 'hover:bg-slate-700 hover:text-white'}`} 
                    title="Translate"
                    onClick={() => setTransformMode('translate')}
                ><Move3d size={18} /></button>
                <button 
                    className={`p-2 rounded transition-colors ${transformMode === 'rotate' ? 'bg-slate-700 text-white' : 'hover:bg-slate-700 hover:text-white'}`} 
                    title="Rotate"
                    onClick={() => setTransformMode('rotate')}
                ><Rotate3d size={18} /></button>
                <button 
                    className={`p-2 rounded transition-colors ${transformMode === 'scale' ? 'bg-slate-700 text-white' : 'hover:bg-slate-700 hover:text-white'}`} 
                    title="Scale"
                    onClick={() => setTransformMode('scale')}
                ><Scaling size={18} /></button>
            </div>
            <div className="bg-slate-800/90 backdrop-blur border border-slate-700 p-2 rounded-lg shadow-xl text-gray-300 flex flex-col gap-1">
                <button 
                    onClick={() => onAction?.(`Generate a variation of the current concept focused on weight reduction`)}
                    className="p-2 hover:bg-slate-700 hover:text-brand-orange rounded transition-colors" title="Optimize Weight"
                >
                    <Weight size={18} />
                </button>
                <button 
                    onClick={() => onAction?.(`Adjust dimensions to be more compact`)}
                    className="p-2 hover:bg-slate-700 hover:text-brand-orange rounded transition-colors" title="Resize"
                >
                    <Ruler size={18} />
                </button>
                <button 
                    onClick={() => onAction?.(`Suggest alternative materials for this concept`)}
                    className="p-2 hover:bg-slate-700 hover:text-brand-orange rounded transition-colors" title="Material Swap"
                >
                    <Wand2 size={18} />
                </button>
            </div>
        </div>

        {/* Live Render Badge */}
        <div className="absolute top-4 right-4 z-20">
            <div className="bg-slate-800/90 backdrop-blur border border-slate-700 px-3 py-1.5 rounded-full shadow-xl flex items-center gap-2 text-xs font-mono text-white">
                <span className="w-2 h-2 rounded-full bg-brand-orange animate-pulse"></span>
                CONCEPT BUILDER
            </div>
        </div>

        {/* 3D Scene Placeholder */}
        <div className="flex-1 flex items-center justify-center relative bg-gradient-to-br from-brand-darkBlue to-[#000] overflow-hidden">
            {data.threeDModel && data.threeDModel.length > 0 ? (
                <Canvas camera={{ position: [5, 5, 5], fov: 50 }}>
                    <ambientLight intensity={0.5} />
                    <directionalLight position={[10, 10, 10]} intensity={1} />
                    <Environment preset="city" />
                    <OrbitControls makeDefault />
                    <Grid infiniteGrid fadeDistance={50} sectionColor="#444" cellColor="#222" />
                    <TransformControls mode={transformMode}>
                        <group>
                            {data.threeDModel.map((primitive, idx) => (
                                <PrimitiveRenderer key={idx} primitive={primitive} />
                            ))}
                        </group>
                    </TransformControls>
                </Canvas>
            ) : (
                <>
                    {/* Grid Floor */}
                    <div 
                        className="absolute inset-0 opacity-20 pointer-events-none" 
                        style={{
                            backgroundImage: 'linear-gradient(#444 1px, transparent 1px), linear-gradient(90deg, #444 1px, transparent 1px)',
                            backgroundSize: '40px 40px',
                            transform: 'perspective(600px) rotateX(60deg) translateY(100px) scale(2)'
                        }}
                    ></div>
                    
                    {/* Object Central Placeholder */}
                    <div className="relative z-10 p-10 border border-dashed border-gray-600 rounded-2xl bg-white/5 backdrop-blur-sm flex flex-col items-center gap-4 text-center max-w-sm animate-in zoom-in duration-500">
                        <div className="relative">
                            <div className="absolute inset-0 bg-brand-orange/20 blur-xl rounded-full"></div>
                            <Box size={64} className="text-brand-orange relative z-10" strokeWidth={1} />
                        </div>
                        <div>
                            <h4 className="text-white font-medium text-xl tracking-tight">{data.conceptName}</h4>
                            <p className="text-xs text-gray-400 mt-2 font-mono uppercase tracking-widest">{data.metrics.dimensions}</p>
                        </div>
                        {/* Simulated markers */}
                        <div className="absolute -right-12 top-0 flex items-center gap-1 bg-slate-800 px-2 py-1 rounded text-[10px] text-white border border-slate-700">
                            <span className="w-1.5 h-1.5 rounded-full bg-brand-darkBlue"></span> Motor Mount
                        </div>
                        <div className="absolute -left-8 bottom-0 flex items-center gap-1 bg-slate-800 px-2 py-1 rounded text-[10px] text-white border border-slate-700">
                             <span className="w-1.5 h-1.5 rounded-full bg-green-400"></span> Base Plate
                        </div>
                    </div>
                </>
            )}
        </div>

        {/* Bottom Metrics Bar */}
        <div className="bg-slate-800 border-t border-slate-700 px-4 py-3 flex justify-between items-center text-xs">
            <div className="flex gap-6 text-gray-400 font-mono">
                <div>MASS: <span className="text-white">{data.metrics.mass}</span></div>
                <div>EST. COST: <span className="text-white">{data.metrics.costEstimate}</span></div>
                {data.metrics.sustainabilityRating && (
                    <div className="flex items-center gap-1">
                        ECO RATING: 
                        <span className={`font-bold ${
                            data.metrics.sustainabilityRating === 'A' ? 'text-green-400' : 
                            data.metrics.sustainabilityRating === 'B' ? 'text-brand-darkBlue' : 'text-yellow-400'
                        }`}>
                            {data.metrics.sustainabilityRating}
                        </span>
                    </div>
                )}
            </div>
            <div className="flex gap-2">
                 <button 
                    onClick={() => handleExportOpenSCAD('STEP')}
                    className="text-brand-orange hover:text-white transition-colors uppercase font-bold tracking-wider"
                 >
                    Export STEP
                 </button>
                 <button 
                    onClick={() => handleExportOpenSCAD('STL')}
                    className="text-brand-orange hover:text-white transition-colors uppercase font-bold tracking-wider ml-4"
                 >
                    Export STL
                 </button>
            </div>
        </div>
      </div>

      {/* RIGHT: Inspector Panel */}
      <div className="w-80 bg-white border-l border-gray-200 flex flex-col shadow-lg z-10">
         <div className="p-5 border-b border-gray-100">
            <h2 className="font-bold text-brand-darkBlue text-lg leading-tight">{data.conceptName}</h2>
            <p className="text-xs text-gray-500 mt-1 line-clamp-3">{data.description}</p>
         </div>

         {/* Tabs */}
         <div className="flex border-b border-gray-100">
            <button 
                onClick={() => setActiveTab('components')}
                className={`flex-1 py-3 text-xs font-bold uppercase tracking-wider border-b-2 transition-colors ${activeTab === 'components' ? 'border-brand-darkBlue text-brand-darkBlue' : 'border-transparent text-gray-400 hover:text-gray-600'}`}
            >
                Part List
            </button>
            <button 
                onClick={() => setActiveTab('rationale')}
                className={`flex-1 py-3 text-xs font-bold uppercase tracking-wider border-b-2 transition-colors ${activeTab === 'rationale' ? 'border-brand-darkBlue text-brand-darkBlue' : 'border-transparent text-gray-400 hover:text-gray-600'}`}
            >
                Rationale
            </button>
         </div>

         {/* Tab Content */}
         <div className="flex-1 overflow-y-auto custom-scrollbar bg-white p-0">
            {activeTab === 'components' ? (
                <div className="divide-y divide-gray-100">
                    {data.components.map((comp, idx) => (
                        <div key={idx} className="p-4 bg-white hover:bg-brand-lightBlue/30 transition-colors group border-b border-gray-50 last:border-0">
                            <div className="flex justify-between items-start mb-1">
                                <span className="font-medium text-brand-darkBlue text-sm">{comp.name}</span>
                                <div className="flex gap-1 flex-wrap">
                                    {comp.sourcing === 'verified_supplier' && (
                                        <span className="text-[10px] bg-green-50 text-green-700 px-1.5 py-0.5 rounded border border-green-100 font-medium">Verified</span>
                                    )}
                                    {comp.sourcing === 'reclaimed' && (
                                        <span className="text-[10px] bg-amber-50 text-amber-700 px-1.5 py-0.5 rounded border border-amber-100 font-medium flex items-center gap-0.5">
                                            <Leaf size={8} /> Reclaimed
                                        </span>
                                    )}
                                    {comp.sourcing === 'custom_manufactured' && (
                                        <span className="text-[10px] bg-purple-50 text-purple-700 px-1.5 py-0.5 rounded border border-purple-100 font-medium flex items-center gap-0.5">
                                            <Hammer size={8} /> Custom
                                        </span>
                                    )}
                                    {comp.sourcing === 'off_the_shelf' && (
                                        <span className="text-[10px] bg-brand-lightBlue text-brand-darkBlue px-1.5 py-0.5 rounded border border-brand-darkBlue/20 font-medium flex items-center gap-0.5">
                                            <Package size={8} /> COTS
                                        </span>
                                    )}
                                </div>
                            </div>
                            
                            <div className="flex justify-between items-center text-xs text-gray-500 mb-2">
                                <span>{comp.category}</span>
                            </div>

                            {/* Off The Shelf Specific Detail Block */}
                            {comp.sourcing === 'off_the_shelf' && (
                                <div className="mt-3 bg-white border border-gray-200 rounded-lg p-3 text-xs shadow-sm">
                                    <div className="text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-2 border-b border-gray-100 pb-1 flex items-center gap-2">
                                        <Package size={10} /> Procurement Data
                                    </div>
                                    <div className="grid grid-cols-2 gap-y-3 gap-x-4 mb-3">
                                        <div>
                                            <div className="text-gray-400 text-[10px] mb-0.5">Supplier</div>
                                            <div className="font-medium text-brand-darkBlue truncate" title={comp.supplier}>{comp.supplier || '-'}</div>
                                        </div>
                                        <div>
                                            <div className="text-gray-400 text-[10px] mb-0.5">MPN</div>
                                            <div className="font-mono text-gray-600 truncate" title={comp.mpn}>{comp.mpn || '-'}</div>
                                        </div>
                                        <div>
                                            <div className="text-gray-400 text-[10px] mb-0.5">Unit Cost</div>
                                            <div className="font-medium text-brand-darkBlue">{comp.unitCost || '-'}</div>
                                        </div>
                                        <div>
                                            <div className="text-gray-400 text-[10px] mb-0.5">Lead Time</div>
                                            <div className="font-medium text-brand-darkBlue">{comp.leadTime || '-'}</div>
                                        </div>
                                    </div>
                                    <div className="flex gap-2">
                                        <button 
                                            onClick={() => onAction?.(`Update sourcing details (Supplier, MPN, Price, Lead Time) for '${comp.name}'`)}
                                            className="flex-1 text-center py-1.5 bg-gray-50 border border-gray-200 text-gray-600 rounded hover:bg-gray-100 hover:text-brand-darkBlue transition-colors text-[10px] font-bold uppercase tracking-wide flex items-center justify-center gap-1"
                                        >
                                            <Settings size={10} />
                                            Edit
                                        </button>
                                        <button 
                                            onClick={() => onOpenParametric && onOpenParametric(comp.mpn || comp.name)}
                                            className="flex-1 text-center py-1.5 bg-brand-darkBlue text-white border border-brand-darkBlue rounded hover:bg-brand-darkBlue transition-colors text-[10px] font-bold uppercase tracking-wide flex items-center justify-center gap-1"
                                        >
                                            <Database size={10} />
                                            Params
                                        </button>
                                    </div>
                                </div>
                            )}

                            {/* Other components specs or if not off-the-shelf, standard view */}
                            {(comp.sourcing !== 'off_the_shelf') && (
                                <div className="space-y-1.5 pt-2 border-t border-gray-100/50">
                                    {comp.supplier && (
                                        <div className="flex items-start gap-2 text-xs">
                                            <span className="text-gray-400 w-12 text-[10px] uppercase tracking-wider font-semibold">Source</span>
                                            <span className="text-brand-darkBlue">{comp.supplier}</span>
                                        </div>
                                    )}
                                    {comp.specs && (
                                        <div className="flex items-start gap-2 text-xs">
                                            <span className="text-gray-400 w-12 text-[10px] uppercase tracking-wider font-semibold">Specs</span>
                                            <span className="text-gray-600">{comp.specs}</span>
                                        </div>
                                    )}
                                    <div className="pt-2">
                                        <button 
                                            onClick={() => onOpenParametric && onOpenParametric(comp.name)}
                                            className="w-full py-1.5 bg-white border border-gray-200 text-gray-500 rounded hover:bg-gray-50 hover:text-brand-darkBlue hover:border-brand-darkBlue transition-colors text-[10px] font-bold uppercase tracking-wide flex items-center justify-center gap-1"
                                        >
                                            <Database size={10} />
                                            View Specs
                                        </button>
                                    </div>
                                </div>
                            )}

                             {/* Notes always visible */}
                            {comp.notes && (
                                <div className="mt-2 text-[11px] text-brand-orange bg-brand-orange/10 p-2 rounded border border-brand-orange/20 flex gap-2">
                                    <Tag size={12} className="flex-shrink-0 mt-0.5" />
                                    <span>{comp.notes}</span>
                                </div>
                            )}
                        </div>
                    ))}
                    
                    {/* Add Component Action */}
                    <div className="p-4">
                        <button 
                            onClick={() => setIsAddModalOpen(true)} 
                            className="w-full py-2 border-2 border-dashed border-gray-200 rounded-lg text-gray-400 font-bold text-xs uppercase tracking-wider hover:border-brand-darkBlue hover:text-brand-darkBlue hover:bg-brand-lightBlue/10 transition-all flex items-center justify-center gap-2"
                        >
                            <Plus size={14} /> Add Component
                        </button>
                    </div>

                    <div className="p-4 pt-0">
                        <h4 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-2">Design Constraints</h4>
                        <div className="flex flex-wrap gap-2">
                            {data.constraints.map((c, i) => (
                                <span key={i} className="text-[10px] bg-gray-200 text-gray-600 px-2 py-1 rounded-full">{c}</span>
                            ))}
                        </div>
                    </div>
                </div>
            ) : (
                <div className="p-5 space-y-6">
                    <div>
                        <h4 className="text-xs font-bold text-brand-darkBlue uppercase tracking-wider mb-2 flex items-center gap-2">
                            <Info size={14} /> Design Logic
                        </h4>
                        <p className="text-sm text-gray-600 leading-relaxed bg-white p-3 rounded-lg border border-gray-100 shadow-sm">
                            {data.rationale}
                        </p>
                    </div>
                    
                    <div>
                        <h4 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2">Specifications</h4>
                        <div className="grid grid-cols-2 gap-3">
                            <div className="bg-white p-3 rounded-lg border border-gray-100 text-center">
                                <div className="text-[10px] text-gray-400 uppercase">Mass</div>
                                <div className="font-mono font-bold text-brand-darkBlue">{data.metrics.mass}</div>
                            </div>
                            <div className="bg-white p-3 rounded-lg border border-gray-100 text-center">
                                <div className="text-[10px] text-gray-400 uppercase">Cost</div>
                                <div className="font-mono font-bold text-brand-darkBlue">{data.metrics.costEstimate}</div>
                            </div>
                        </div>
                    </div>
                </div>
            )}
         </div>

         {/* Footer Actions */}
         <div className="p-4 bg-white border-t border-gray-200">
            <button className="w-full flex items-center justify-center gap-2 bg-brand-orange text-white font-bold py-2 rounded-lg text-sm hover:bg-orange-600 transition-colors">
                <Share2 size={16} /> Share Concept
            </button>
         </div>
      </div>
    </div>
  );
};
