import React from 'react';
import { DocumentData } from '../../types';
import { FileText, Download, Printer } from 'lucide-react';

interface DocumentViewProps {
  data: DocumentData;
}

export const DocumentView: React.FC<DocumentViewProps> = ({ data }) => {
  return (
    <div className="flex flex-col h-full bg-brand-gray/30">
       {/* Toolbar */}
      <div className="flex items-center justify-between px-6 py-4 border-b border-brand-darkBlue/5 bg-white shadow-sm z-10">
         <div className="flex items-center gap-2.5 text-brand-darkBlue">
            <FileText size={18} className="text-brand-blue" />
            <span className="font-semibold text-sm tracking-wide">Engineering Doc</span>
         </div>
         <div className="flex gap-2">
            <button className="p-2 hover:bg-brand-gray rounded-lg text-gray-500 hover:text-brand-blue transition-colors" title="Print"><Printer size={18} /></button>
            <button className="p-2 hover:bg-brand-gray rounded-lg text-gray-500 hover:text-brand-blue transition-colors" title="Download PDF"><Download size={18} /></button>
         </div>
      </div>

      {/* Document Content */}
      <div className="flex-1 overflow-auto custom-scrollbar p-6 md:p-12">
        <div className="max-w-3xl mx-auto bg-white shadow-float rounded-2xl border border-brand-darkBlue/5 min-h-[800px] p-10 md:p-16">
            <div className="border-b-2 border-brand-blue/20 pb-6 mb-10">
                <h1 className="font-serif text-4xl font-semibold text-brand-darkBlue leading-tight tracking-tight">{data.title}</h1>
                <div className="mt-6 flex justify-between text-[11px] font-mono text-gray-400 uppercase tracking-widest">
                    <span>Buildables Auto-Gen</span>
                    <span>{new Date().toLocaleDateString()}</span>
                </div>
            </div>

            <div className="space-y-10 font-serif text-gray-700 leading-relaxed text-lg">
                {data.sections.map((section, idx) => (
                    <div key={idx}>
                        <h2 className="font-sans text-sm font-bold uppercase tracking-widest text-brand-blue mb-4">{section.heading}</h2>
                        <div className="prose prose-stone max-w-none text-base whitespace-pre-wrap">
                            {section.body}
                        </div>
                    </div>
                ))}
            </div>

            <div className="mt-20 pt-10 border-t border-brand-darkBlue/5 text-center">
                 <p className="text-xs text-gray-400 font-sans tracking-wide">
                    Generated by Buildables v3 Engineering Copilot. 
                    <br/><span className="text-amber-600/70">Review required before manufacturing release.</span>
                 </p>
            </div>
        </div>
      </div>
    </div>
  );
};